name: Context Testing

on: push

jobs:
    dump_context_to_log:
        runs-on: ubuntu-latest
        steps:
        - name: Dump Github Context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        
        - name: Dump Job Context
          env:
            JOB_CONTEXT: ${{ toJson(job) }}
          run: echo "$JOB_CONTEXT"

        - name: Dump Steps Context
          env:
            STEPS_CONTEXT: ${{ toJson(steps) }}
          run: echo "$STEPS_CONTEXT"

        - name: Dump Runner Context
          env:
            RUNNER_CONTEXT: ${{ toJson(runner) }}
          run: echo "$RUNNER_CONTEXT"
        
        - name: Dump Secret Context
          env:
            SECRET_CONTEXT: ${{ toJson(secrets) }}
          run: echo "$SECRET_CONTEXT"