name: Generate ASCII Artwork

on: push

jobs:
  ascii-job:
    runs-on: ubuntu-lastest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay on CMD
      run: cowsay -f dragon "Run cowsay for cover, I am a Dragon....RAWR" >> dragon.txt

    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

    - name: Read Files
      run: cat dragon.txt

    - name: List All Files
      run: ls -ltra
