name: Matrix Strategy

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            fail-fast: false # by default it is true
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, ubuntu-20.40, windows-latest]
                images: [hello-world, alpine]

                exclude:
                    - name: alpine
                      os: windows-latest

                include:
                    - name: amd64/alpine
                      os: ubuntu-20.40
        
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: |
            docker info
        
        - name: Run Image on ${{ matrix.os}}
          run: |
            docker run ${{ matrix.images }}